# Generated by Django 4.2.2 on 2023-06-06 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TWIB1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='link',
            field=models.CharField(default=django.utils.timezone.now, max_length=2080),
            preserve_default=False,
        ),
    ]
