# Generated by Django 4.2.2 on 2023-06-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TWIB1', '0003_content_type_webpage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='rate',
            field=models.FloatField(),
        ),
    ]
