# Generated by Django 4.1.7 on 2023-08-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TWIB1', '0006_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='typ2',
            field=models.CharField(default='men', max_length=200),
        ),
    ]
