# Generated by Django 3.2.13 on 2023-08-31 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TWIB1', '0008_user_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='typ2',
        ),
    ]
