# Generated by Django 3.2.13 on 2023-08-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TWIB1', '0009_remove_content_typ2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='rate',
            field=models.CharField(max_length=2080),
        ),
    ]
