# Generated by Django 4.1.5 on 2023-09-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TWIB1", "0010_alter_content_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="rate",
            field=models.FloatField(),
        ),
    ]
